from __future__ import annotations
from pathlib import Path
from argly.app import App
from pprint import pformat
from typing import Optional
from os import chmod, replace
from argly._parser import Node
from argparse import ArgumentParser
from sys import path as module_path
from collections.abc import Sequence
from tempfile import NamedTemporaryFile


def _rows(items: list[tuple[str, str]]) -> list[str]:
    width = min(max((len(label) for label, _ in items), default=0), 36)
    rows = []
    for label, description in items:
        if len(label) > width:
            rows.append(f'  {label}\n{" " * (width + 4)}{description}')
        else:
            rows.append(f'  {label:<{width}}  {description}'.rstrip())

    return rows


def render(name: str, node: Node) -> str:
    """Render one help page from compiled metadata without importing handlers."""
    invocation = name + (' ' + node.path if node.path else '')
    usage = f'Usage: {invocation} [options]'
    if node.children:
        usage += ' <command>' if node.handler is None else ' [command]'

    for argument in node.arguments:
        label = argument['metavar'] + ('...' if argument['multiple'] else '')
        usage += ' ' + (f'<{label}>' if argument['required'] else f'[{label}]')

    lines = [usage]
    if node.summary:
        lines.extend(('', node.summary))

    if node.children:
        lines.extend(('', 'Commands:'))
        lines.extend(
            _rows(
                [
                    (name, child.summary.splitlines()[0] if child.summary else '')
                    for name, child in sorted(node.children.items())
                ]
            )
        )

    if node.arguments:
        lines.extend(('', 'Arguments:'))
        lines.extend(_rows([(item['metavar'], item['help']) for item in node.arguments]))

    lines.extend(('', 'Options:'))
    rows = [('-h, --help', 'Show this help and exit')]
    inherited_names: set[str] = set()
    for child in node.children.values():
        inherited_names.update(option['dest'] for option in child.options)

    for option in node.options:
        names = [
            name for name in option['names'] if node.windows_options or not name.startswith('/')
        ]
        label = ', '.join(names)
        if option['action'] == 'value':
            label += ' ' + option['metavar']

        details = [option['help']] if option['help'] else []
        if option['required']:
            details.append('(required)')
        elif option['default'] is not None:
            details.append(f'[default: {option["default"]}]')

        if option['choices'] is not None:
            details.append('[choices: ' + ', '.join(map(str, option['choices'])) + ']')

        if option['multiple'] or option['action'] == 'count':
            details.append('(repeatable)')

        if option['dest'] in inherited_names:
            details.append('(also applies to subcommands)')

        rows.append((label, ' '.join(details)))

    lines.extend(_rows(rows))

    return '\n'.join(lines) + '\n'


def source(app: App, *, help_only: bool = False) -> str:
    """Generate an import-free module with static help and optional registry data."""
    if not help_only:
        for entry in app.registry['commands']:
            handler = entry['handler']
            if handler and ('<locals>' in handler or handler.startswith('__main__:')):
                raise ValueError('generated handlers must be importable module-level functions')

    lines = ['# Generated by argly gen. Regenerate after changing command definitions.', '']
    if not help_only:
        lines.extend(('REGISTRY = ' + pformat(app.registry, width=100, sort_dicts=True), ''))

    lines.append('HELP = {')
    for path, node in sorted(app._nodes.items()):
        lines.append(f'    {path!r}: {render(app.name, node)!r},')

    lines.extend(('}', '', '', 'def get_help(path):', '    return HELP.get(path)', ''))

    return '\n'.join(lines)


def generate(app: App, output: Path, *, check: bool = False, help_only: bool = False) -> bool:
    """Write atomically, or check freshness. Return False for stale check output."""
    if output.suffix != '.py':
        raise ValueError('help output must be a .py file')

    data = source(app, help_only=help_only).encode('utf-8')
    try:
        existing = output.read_bytes()
    except FileNotFoundError:
        existing = None

    if existing == data:
        return True

    if check:
        return False

    output.parent.mkdir(parents=True, exist_ok=True)
    temporary: Optional[Path] = None
    try:
        with NamedTemporaryFile(
            dir=output.parent, prefix='.argly-', suffix='.tmp', delete=False
        ) as stream:
            written_path = Path(stream.name)
            temporary = written_path
            stream.write(data)

        if output.exists():
            chmod(written_path, output.stat().st_mode)

        replace(written_path, output)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)

    return True


def main(args: Optional[Sequence[str]] = None, *, prog: Optional[str] = None) -> int:
    """Discover command definitions and generate a standalone Python module."""
    parser = ArgumentParser(
        prog=prog, description='Generate static argly help and a lazy command registry.'
    )
    parser.add_argument(
        '--package', required=True, help='Importable package containing command modules'
    )
    parser.add_argument('--name', required=True, help='Application name displayed in help')
    parser.add_argument('--output', type=Path, required=True, help='Generated .py module')
    parser.add_argument(
        '--windows-options', action='store_true', help='Enable explicit slash aliases'
    )
    parser.add_argument('--help-only', action='store_true', help='Omit command registry metadata')
    parser.add_argument('--check', action='store_true', help='Check freshness without writing')
    options = parser.parse_args(args)
    directory = str(Path.cwd())
    added_path = directory not in module_path
    if added_path:
        module_path.insert(0, directory)

    try:
        app = App.discover(options.name, options.package, windows_options=options.windows_options)
        current = generate(app, options.output, check=options.check, help_only=options.help_only)
    except (ValueError, OSError, ImportError, TypeError, NameError) as error:
        parser.exit(2, f'argly gen: {error}\n')
    finally:
        if added_path:
            module_path.remove(directory)

    if not current:
        parser.exit(1, f'argly gen: {options.output} is missing or stale; regenerate it\n')

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
