def get_registry():
    return {'version': 1,
     'name': 'tool',
     'windows_options': True,
     'commands': [{'path': '',
                   'summary': 'Manage named remotes.',
                   'handler': None,
                   'options': [{'dest': 'verbose',
                                'type': 'int',
                                'multiple': False,
                                'nullable': False,
                                'choices': None,
                                'default': 0,
                                'required': False,
                                'help': 'Increase verbosity',
                                'metavar': 'VERBOSE',
                                'names': ['--verbose', '-v', '/V'],
                                'action': 'count'}],
                   'arguments': [],
                   'bindings': {'verbose': 'verbose'}},
                  {'path': 'remote',
                   'summary': 'Inspect and update remotes.',
                   'handler': None,
                   'options': [{'dest': 'token',
                                'type': 'str',
                                'multiple': False,
                                'nullable': True,
                                'choices': None,
                                'default': None,
                                'required': False,
                                'help': 'Authentication token',
                                'metavar': 'TOKEN',
                                'names': ['--token', '-t', '/Token'],
                                'action': 'value'}],
                   'arguments': [],
                   'bindings': {'token': 'token'}},
                  {'path': 'remote add',
                   'summary': 'Show how a remote would be added.',
                   'handler': 'examples.remote_cli.commands.remote:add',
                   'options': [{'dest': 'url',
                                'type': 'str',
                                'multiple': False,
                                'nullable': False,
                                'choices': None,
                                'default': None,
                                'required': True,
                                'help': 'Remote URL',
                                'metavar': 'URL',
                                'names': ['--url', '-u', '/URL', '/U', '/u'],
                                'action': 'value'},
                               {'dest': 'force',
                                'type': 'bool',
                                'multiple': False,
                                'nullable': False,
                                'choices': None,
                                'default': False,
                                'required': False,
                                'help': 'Allow replacing an existing remote',
                                'metavar': 'FORCE',
                                'names': ['--force', '-f'],
                                'action': 'flag'}],
                   'arguments': [{'dest': 'name',
                                  'type': 'str',
                                  'multiple': False,
                                  'nullable': False,
                                  'choices': None,
                                  'default': None,
                                  'required': True,
                                  'help': 'Remote name',
                                  'metavar': 'NAME'}],
                   'bindings': {'name': 'name',
                                'url': 'url',
                                'verbose': 'verbose',
                                'token': 'token',
                                'force': 'force'}},
                  {'path': 'remote list',
                   'summary': 'Show example remotes.',
                   'handler': 'examples.remote_cli.commands.remote:list_remotes',
                   'options': [],
                   'arguments': [],
                   'bindings': {'verbose': 'verbose'}}]}
